name: Prodigy Photography
favicon: null
layout_spectrum: 0.24609
typography_spectrum: 0.36652
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bb7600'
    - '#fefefe'
    - '#070000'
    - '#263f00'
    - '#e7a79d'
  brandStrength: 0.6869909844826907
  lightness: 0.37817940139211714
  saturation: 0.25
  rhythmicContrast: 0.09372134483419359
purpose: []
