name: Prodigy Photography
favicon: null
layout_spectrum: 0.49879
typography_spectrum: 0.38939866912551224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dcddf1'
    - '#393f4f'
    - '#8ea8cd'
    - '#f7a477'
  brandStrength: 0.6869909844826907
  lightness: 0.37817940139211714
  saturation: 0.6631206572055817
  rhythmicContrast: 0.09372134483419359
purpose: []
